// Generated by Framer (f21d278)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "19galtk", mediaQuery: "(min-width: 1200px)"}, {hash: "1hovzpu", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "doh1q", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-0UQ9p", title: "Team", viewport: "width=device-width"}
}

export const metadataVersion = 1