// Generated by Framer (f21d278)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "72rtr7", mediaQuery: "(min-width: 1200px)"}, {hash: "1oiilo", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1ihnuzc", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-DIeXz", title: "Home", viewport: "width=device-width"}
}

export const metadataVersion = 1