// Generated by Framer (f0648f9)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "o4ub19", mediaQuery: "(min-width: 1200px)"}, {hash: "1dt8qf3", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "hhsolo", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-a3T6j", title: "Careers", viewport: "width=device-width"}
}

export const metadataVersion = 1