// Generated by Framer (f0648f9)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1wattcr", mediaQuery: "(min-width: 1200px)"}, {hash: "19j3jsf", mediaQuery: "(min-width: 810px) and (max-width: 1199.98px)"}, {hash: "1yd7oiw", mediaQuery: "(max-width: 809.98px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-s9uPa", title: "Careers", viewport: "width=device-width"}
}

export const metadataVersion = 1